/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'galleryImages' : Array<string>,
  'status' : EventStatus,
  'title' : string,
  'creationTimestamp' : bigint,
  'shortDescription' : string,
  'eventDateTime' : bigint,
  'posterImage' : string,
  'fullDescription' : string,
  'videoUrl' : string,
  'ticketPrice' : number,
}
export type EventStatus = { 'upcoming' : null } |
  { 'past' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, bigint, number, string, Array<string>, string],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventById' : ActorMethod<[bigint], [] | [Event]>,
  'getRecentUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubscribers' : ActorMethod<[], Array<string>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'toggleEventStatus' : ActorMethod<[bigint], undefined>,
  'updateEvent' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      number,
      string,
      Array<string>,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];