/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'past' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'galleryImages' : IDL.Vec(IDL.Text),
  'status' : EventStatus,
  'title' : IDL.Text,
  'creationTimestamp' : IDL.Int,
  'shortDescription' : IDL.Text,
  'eventDateTime' : IDL.Int,
  'posterImage' : IDL.Text,
  'fullDescription' : IDL.Text,
  'videoUrl' : IDL.Text,
  'ticketPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventById' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getRecentUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'toggleEventStatus' : IDL.Func([IDL.Nat], [], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventStatus = IDL.Variant({ 'upcoming' : IDL.Null, 'past' : IDL.Null });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'galleryImages' : IDL.Vec(IDL.Text),
    'status' : EventStatus,
    'title' : IDL.Text,
    'creationTimestamp' : IDL.Int,
    'shortDescription' : IDL.Text,
    'eventDateTime' : IDL.Int,
    'posterImage' : IDL.Text,
    'fullDescription' : IDL.Text,
    'videoUrl' : IDL.Text,
    'ticketPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventById' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getRecentUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'toggleEventStatus' : IDL.Func([IDL.Nat], [], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };